  version: 2

models:
  - name: dim_customers
    description: Customers dimension table

    columns:
      - name: CUSTOMER_WID
        description: Table primary key
        tests:
          - not_null
          - dbt_expectations.expect_column_values_to_be_unique
          
          
          

  - name: dim_geography
    description: Geography dimension table

    columns:
      - name: GEO_WID
        description: Table primary key
        tests:
          - not_null
          - unique
          


  - name: dim_products
    description: Products dimension table

    columns:
      - name: PRODUCT_WID
        description: Table primary key
        tests:
          - not_null
          - unique
          


  - name: fact_orders
    description: Orders fact table

    columns:
      - name: PRODUCT_WID
        description: Table foreign key

    columns:
      - name: CUSTOMER_WID
        description: Table foreign key

    columns:
      - name: GEO_WID
        description: Table foreign key

    columns:
      - name: ORDER_NUMBER
        description: Table primary key

    columns:
      - name: ORDER_LINE_NUMBER
        description: Table primary key